#!/usr/bin/env python3
"""Narration-first Short: execute and repair an N+1 query generated by an AI agent."""
from __future__ import annotations
import argparse, hashlib, json, math, sqlite3, subprocess, tempfile
from pathlib import Path
import numpy as np
import soundfile as sf
from kokoro_onnx import Kokoro
from PIL import Image,ImageDraw,ImageFilter,ImageFont,ImageChops

W,H,FPS=540,960,30
FONT='/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'; BOLD='/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'; MONO='/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf'
C={'bg':'#F4EFE5','ink':'#17233B','blue':'#185ADB','coral':'#F05D5E','gold':'#F6AE2D','green':'#16856B','paper':'#FFFDF8','muted':'#64748B'}
SEGMENTS=(
 "An AI agent wrote a clean endpoint. But one hidden loop turned one request into one hundred and one database queries.",
 "Here is the real test. Load one hundred orders, then fetch each customer inside the loop. The counter reaches one hundred and one.",
 "Keep the exact data. Replace the loop with one join, so the database resolves every customer in the same query.",
 "Run the benchmark again. One query returns the same one hundred rows, with the same total and the same first customer.",
 "The regression test now rejects any implementation above two queries. The slow version fails. The joined version passes.",
 "AI can draft code quickly. Production needs executable evidence: query count, result equality, and a performance budget in continuous integration."
)

def benchmark():
 db=sqlite3.connect(':memory:'); count=0
 def trace(sql):
  nonlocal count
  if sql.lstrip().upper().startswith('SELECT'): count+=1
 db.set_trace_callback(trace); c=db.cursor()
 c.executescript('CREATE TABLE customers(id INTEGER PRIMARY KEY,name TEXT);CREATE TABLE orders(id INTEGER PRIMARY KEY,customer_id INTEGER,total INTEGER);')
 c.executemany('INSERT INTO customers VALUES(?,?)',[(i,f'Customer {i:03d}') for i in range(1,101)])
 c.executemany('INSERT INTO orders VALUES(?,?,?)',[(i,i,10+i) for i in range(1,101)]);db.commit()
 count=0; orders=c.execute('SELECT id,customer_id,total FROM orders ORDER BY id').fetchall(); slow=[]
 for oid,cid,total in orders: slow.append((oid,c.execute('SELECT name FROM customers WHERE id=?',(cid,)).fetchone()[0],total))
 slow_queries=count
 count=0; fast=c.execute('SELECT o.id,c.name,o.total FROM orders o JOIN customers c ON c.id=o.customer_id ORDER BY o.id').fetchall();fast_queries=count
 result={'orders':len(fast),'slowQueries':slow_queries,'fastQueries':fast_queries,'sameRows':slow==fast,'sameTotal':sum(x[2] for x in slow)==sum(x[2] for x in fast),'firstCustomer':fast[0][1]}
 assert result=={'orders':100,'slowQueries':101,'fastQueries':1,'sameRows':True,'sameTotal':True,'firstCustomer':'Customer 001'}
 return result
def ff(n,b=False,m=False):return ImageFont.truetype(MONO if m else BOLD if b else FONT,n)
def ease(x):x=max(0,min(1,x));return x*x*(3-2*x)
def wrap(d,s,f,w):
 out=[];line=''
 for word in s.split():
  trial=(line+' '+word).strip()
  if d.textbbox((0,0),trial,font=f)[2]<=w:line=trial
  else:out.append(line);line=word
 if line:out.append(line)
 return out
class Frame:
 def __init__(self,t):
  self.t=t;self.bg=Image.new('RGB',(W,H),C['bg']);self.fx=Image.new('RGBA',(W,H));self.ui=Image.new('RGBA',(W,H));self.mask=Image.new('L',(W,H));self.d=ImageDraw.Draw(self.ui);self.f=ImageDraw.Draw(self.fx);self.md=ImageDraw.Draw(self.mask);self.boxes=[]
 def text(self,x,y,s,n=20,c=None,b=False,m=False,anchor=None):
  face=ff(n,b,m);box=self.d.textbbox((x,y),s,font=face,anchor=anchor)
  if not(24<=box[0] and box[2]<=516 and 52<=box[1] and box[3]<=900):raise ValueError((self.t,s,box))
  self.md.rectangle((box[0]-5,box[1]-4,box[2]+5,box[3]+4),fill=255);self.boxes.append(box);self.d.text((x,y),s,font=face,fill=c or C['ink'],anchor=anchor)
 def finish(self):
  a=self.fx.getchannel('A');removed=np.count_nonzero(np.asarray(ImageChops.multiply(a,self.mask)));a=ImageChops.multiply(a,ImageChops.invert(self.mask));self.fx.putalpha(a);overlap=np.count_nonzero(np.asarray(ImageChops.multiply(a,self.mask)));im=self.bg.convert('RGBA');im.alpha_composite(self.fx);im.alpha_composite(self.ui);return im.convert('RGB'),overlap,removed
def draw(t,timeline,proof):
 fr=Frame(t);d=fr.d;f=fr.f
 i=next((j for j,s in enumerate(timeline) if t<s['end']+.12),5);seg=timeline[i];p=ease((t-seg['start'])/max(.1,seg['end']-seg['start']))
 fr.text(30,57,'AI CODE REVIEW / DATABASE LAB',14,C['blue'],True)
 fr.text(30,91,'One endpoint. How many queries?',24,C['ink'],True)
 # Physical data path: packets stream from request through the query counter into result rows.
 f.line((58,183,482,183),fill=C['blue'],width=4)
 for k in range(7):
  q=((t*.55+k/7)%1);x=58+424*q;f.ellipse((x-5,178,x+5,188),fill=C['gold'])
 d.rounded_rectangle((28,135,512,733),22,fill=C['paper'],outline=C['ink'],width=2)
 fr.text(48,155,'GET /orders',21,C['ink'],True,True)
 # editor and code actually type in with narration
 joined=i>=2;code_slow=['orders = db.query("SELECT * FROM orders")','for order in orders:','  customer = db.query("SELECT name ...")']
 code_fast=['rows = db.query("SELECT o.id, c.name, o.total",','  "FROM orders o JOIN customers c",','  "ON c.id = o.customer_id")']
 lines=code_fast if joined else code_slow
 show=max(1,min(3,int(p*4))) if i in (1,2) else 3
 d.rounded_rectangle((46,218,494,390),14,fill=C['ink'])
 for j,line in enumerate(lines[:show]):fr.text(63,244+j*43,line,12,C['paper'],False,True)
 if i==2:f.rectangle((60+int(405*p),374,64+int(405*p),382),fill=C['gold'])
 # causal counter rises for slow run and falls only after source change
 target=101 if i<2 else 1
 if i==1:value=max(1,round(101*p))
 elif i==2:value=round(101-(100*p))
 else:value=target
 fr.text(48,425,'QUERY COUNTER',14,C['muted'],True)
 fr.text(48,452,str(value),68,C['coral'] if value>2 else C['green'],True,True)
 fr.text(192,488,'SELECT statements',18,C['ink'])
 # query trail shows actual multiplicity, not decorative particles
 bars=12 if value>2 else 1
 for k in range(bars):
  y=552+k*10;length=360*(1-k/(bars+4));f.rounded_rectangle((64,y,64+length,y+5),3,fill=C['coral'] if value>2 else C['green'])
 fr.text(48,689,'100 ORDERS',15,C['ink'],True)
 fr.text(475,689,'SAME ROWS' if joined else '101 SELECTS',15,C['green'] if joined else C['coral'],True,anchor='ra')
 # terminal assertions appear from executed benchmark result
 if i>=3:
  d.rounded_rectangle((28,748,512,845),16,fill='#17233B')
  labels=[f"queries {proof['slowQueries']} → {proof['fastQueries']}",f"rows {proof['orders']}  equality PASS",'budget <= 2  PASS']
  show=1 if i==3 else max(1,min(3,1+int(p*3))) if i==4 else 3
  active=-1 if i<5 else min(2,int(p*3))
  for j,s in enumerate(labels[:show]):
   if j==active:d.rounded_rectangle((42,760+j*27,480,786+j*27),7,outline=C['gold'],width=2)
   fr.text(50,769+j*27,s,15,C['green'] if 'PASS' in s else C['paper'],True,True)
 # captions: measured segment time, 5-word windows
 words=seg['text'].split();active=min(len(words)-1,max(0,int(p*len(words))));group=words[(active//5)*5:(active//5)*5+5];rows=wrap(d,' '.join(group),ff(22,True),480)
 for j,row in enumerate(rows[:2]):fr.text(270,845+j*27,row,22,C['ink'],True,anchor='ma')
 d.rounded_rectangle((28,925,512,932),4,fill='#D6D0C5');d.rounded_rectangle((28,925,28+484*t/timeline[-1]['end'],932),4,fill=C['blue'])
 return fr
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--model',required=True);ap.add_argument('--voices',required=True);ap.add_argument('--output',type=Path,required=True);a=ap.parse_args();out=a.output;out.mkdir(parents=True,exist_ok=True)
 proof=benchmark();(out/'proof-output.json').write_text(json.dumps(proof,indent=2)+'\n')
 k=Kokoro(a.model,a.voices);parts=[];timeline=[];cursor=0.;gap=np.zeros(int(24000*.12),np.float32)
 for i,text in enumerate(SEGMENTS):
  audio,rate=k.create(text,voice='af_heart',speed=1.04,lang='en-us',sentence_pause=.17,clause_pause=.07);audio=np.asarray(audio,np.float32);start=cursor;end=start+len(audio)/rate;timeline.append({'index':i,'text':text,'start':round(start,4),'end':round(end,4)});parts.append(audio);cursor=end
  if i<len(SEGMENTS)-1:parts.append(gap);cursor+=len(gap)/rate
 voice=np.concatenate(parts);sf.write(out/'voice.wav',voice,24000);duration=len(voice)/24000
 (out/'timeline.json').write_text(json.dumps({'voice':'Kokoro stock af_heart','segments':timeline,'duration':round(duration,4)},indent=2)+'\n')
 n=math.ceil(duration*FPS);proc=subprocess.Popen(['ffmpeg','-y','-v','error','-f','rawvideo','-pix_fmt','rgb24','-s',f'{W}x{H}','-r',str(FPS),'-i','-','-vf','scale=1080:1920:flags=lanczos','-an','-c:v','libx264','-threads','2','-preset','fast','-crf','18','-pix_fmt','yuv420p',str(out/'visuals.mp4')],stdin=subprocess.PIPE)
 overlap=removed=maxboxes=0;samples=[]
 for frame_no in range(n):
  fr=draw(frame_no/FPS,timeline,proof);im,o,r=fr.finish();overlap+=o;removed+=r;maxboxes=max(maxboxes,len(fr.boxes));proc.stdin.write(im.tobytes())
  if frame_no%(FPS*5)==0:samples.append(im.resize((270,480)))
  if frame_no==round(timeline[3]['start']*FPS):im.resize((1080,1920),Image.Resampling.LANCZOS).save(out/'thumbnail.jpg',quality=94)
 proc.stdin.close();assert proc.wait()==0
 final=out/'video.mp4';subprocess.run(['ffmpeg','-y','-v','error','-i',str(out/'visuals.mp4'),'-i',str(out/'voice.wav'),'-filter:a','highpass=f=70,acompressor=threshold=-20dB:ratio=2.2:attack=8:release=150,loudnorm=I=-16:TP=-1.5:LRA=7','-c:v','copy','-c:a','aac','-b:a','192k','-shortest','-movflags','+faststart',str(final)],check=True)
 sheet=Image.new('RGB',(270*4,480*math.ceil(len(samples)/4)),C['bg'])
 for j,im in enumerate(samples):sheet.paste(im,((j%4)*270,(j//4)*480))
 sheet.save(out/'contact-sheet.jpg',quality=90)
 report={'passed':overlap==0,'framesChecked':n,'intersectingPixels':int(overlap),'effectPixelsRemovedByTextMasks':int(removed),'textBoundsCheckedEveryFrame':True,'maxTextBoxesPerFrame':maxboxes,'videoSha256':hashlib.sha256(final.read_bytes()).hexdigest()};(out/'effect-overlap-report.json').write_text(json.dumps(report,indent=2)+'\n')
 print(json.dumps({'duration':duration,'proof':proof,'composition':report}))
if __name__=='__main__':main()
